Выполнен учебный проект: холст
htmlacademy-javascript/104923-code-and-magick-21 pull request #2
Opened 2020-09-19 15:09 UTC by vlastavetra

2020-09-21 18:29 UTC, justiszley requested changes

2020-09-21 18:29 UTC, justiszley commented on js/stat.js
> +  for (let i = 0; i < names.length; i++) {
Чтобы читать было проще, стоит разбить содержимое цикла на функции: одна будет писать текст на определённых координатах, можно также сделать функции "Текст над столбцом" и "Текст под столбцом", которые будут отличаться y-координатой и вызывать функцию отрисовки текста; Другая функция пусть рисует столбцы.

2020-09-21 21:19 UTC, vlastavetra commented on js/game.js
> +/* eslint-disable no-undef */
Я не удержалась и написала еще в "Вопросы авторам" по этой проблеме.
Проблему с линтерами посоветовали решить путем добавления js/game.js в .eslintignor
Так и сделаю, чтобы не вмешиваться в движок совсем

2020-09-22 06:59 UTC, justiszley commented on js/stat.js
> +    let drawBar = (userNumber, userName, userTime) => {
На каждую проход в цикле будет создаваться новая функция - это нехорошо.
Надо объявление функций вынести за цикл

2020-09-22 07:01 UTC, justiszley commented on js/stat.js
> +    let drawBar = (userNumber, userName, userTime) => {
И не просто за цикл, а лучше за renderStatistics, где у тебя getMaxElement и renderCloud
Иначе на каждый вызов renderStatistics также будут заново создаваться функции

2020-09-22 18:38 UTC, merged